# 序曲

在 `node.js` 中，打开一个文件的格局与别处是不同的：

```javascript
const fs = require('fs');
fs.readFile(__filename, (err, data) => {
    if (err) {
        console.error(\"Failed to read file beacuse: \", e);
        process.exit(1);
    }
    console.log(\"data readed: \n\" + data);
})
```

读文件的函数不再返回值，而是让我们传递一个“回调函数”，供文件 IO 完成之后执行。

一些人会管这个叫做 **continuation passing style** ，即 **CPS**。其中的 continuation 指的就是那个冗长的回调函数，continuation 在这里的意思是“计算的延续”。

将函数变成这样并不是没有意义——比如可以暂存完成读文件之后的代码，马上执行接下来的代码，然后等到硬件完成 IO 之后重启（在我的印象中，大部分操作系统都会提供这样的机制，诸如 Linux 的 `epoll` 或者 BSD 的 `kqueue`）。于是能够让整个程序运行时无需阻塞地等待硬件 IO，进而多路复用有限的几个线程——这样的“多线程”完全是在用户空间中实现的，所以能够拥有相当高的效率（当然也不是没有代价）。 

# 回调地狱

罪恶的根源之一在于：函数的返回现在用一种不同于往常的方式给出——即是将“返回值”注入到回调函数的参数中去。

在过去，天还很蓝，水还很清。时间过得很慢。

所有的函数返回都是由调用者获得之后，自己决定该啥时候使用它——他可以慢悠悠地读到的文件解析成为 JSON，或者将其中每一个 *fuck* 变成 *love* ，然后再将它返回给调用自己的人。

```javascript
const fs = require('fs');
function peaceAndLove(file) {
  const stream = fs.readFileSync(file);
  const fileContent = stream.toString();
  return fileContent.replace(/fuck/i, \"love\");
}
```

现在，**在 CPS 的淫威之下**，这样的田园牧歌般的函数已经变成不可能了；因为我们没有捕获外部函数 `return` 关键字的力量，如今的我们不可能在回调函数中切断原先函数的控制流，于是我们必须把自己的函数也给 CPS 化：

```javascript
const fs = require('fs');
function peaceAndLove(file, callback) {
	fs.readFile(file, (err, stream) => {
  /* 这里多了一层缩进。 */
    if(err) {
      /* 错误处理代码必须和正常执行的代码写在一起了，而且失去了默认行为。*/
      callback(err);
      return;
    }
  	const fileContent = stream.toString();
  	callback(null, fileContent.replace(/fuck/i, \"love\"));
  })         
  /* 我们的函数返回空值，传递值的方式变成了调用传入的 callback。 */
}
```

这样之后，我们的代码结构发生了一些变化：

- 传输匿名的回调函数会让缩进多上一层。
- 没有了 try-catch 结构，因此错误失去了默认行为——向上级调用者抛出；因此必须手动来处理它：即将其传给回调函数。
- 我们的函数变得不太像是函数了：它没有返回值，完全靠副作用来完成计算。

一旦代码的结构变得复杂，我们需要组合多个这样的返回值的时候，马上就会发生有些可怕的事情：

```javascript
const fs = require('fs');
function concatFile3(file1, file2, file3, callback) {
  fs.readFile(file1, (err1, data1) => {
    fs.readFile(file2, (err2, data2) => {
      fs.readFile(file3, (err3, data3) => {
        let e;
        if (e = err1 || err2 || err3) {
          callback(e);
          return;
        }
        callback(null, `${data1}${data2}${data3}`);
      })
    })
  })
}
```

这种层层叠叠的代码非常让人沮丧：它和我们熟悉的编程差得太远了——诡异的返回方式、完全冗余的错误处理、> 号形状的代码……回头看看，排除掉一些觉得这样很酷的奇才，过去的生活大概大家都会怀念吧：

```javascript
const fs = require('fs');
function concatFile3(file1, file2, file3) {
  const data1 = fs.readFileSync(file1);
  const data2 = fs.readFileSync(file2);
  const data3 = fs.readFileSync(file3);
  return `${data1}${data2}${data3}`;
}
```

是时候了。拿起我们的智慧和想象力，在 CPS 统治的世界之下夺回我们的故乡吧。虽然道阻且长，虽然颇为迷惘，但我们还有强大的伙伴：First-class Functions——我们能够将函数作为值传递，而函数恰恰是编程语言的世界中数不尽奇迹的根源之一。

于是出发吧。我们的工作最终会将异步的 `concatFile3` 变得和同步的 `concatFile3` 非常相似，但是仍旧保持着异步非阻塞调用的特性。我们会在异步的世界中找到让人怀念的归宿、还有一种对于这些类型——持有上下文的值们的共同类型的通用抽象方法。

# 重新拥有返回值

CPS 函数仅仅使用回调函数来描绘接下来的计算，我们所需要的“返回值”被封存在了回调函数的参数之中。

这里，一种在函数式语言中广泛使用的技术——局部施用（partial application）能够帮到我们。给出一个函数和几个参数，将这几个参数“绑定”到那个函数中去，然后产生一个新的函数。这时候，新生的函数的前几个参数都会以我们刚才的那几个参数作为“默认值”，我们只需要给出剩余的参数即可。

另外值得一提的事情是，局部施用的行为几乎就是 Javascript 中 `bind` 函数的行为。

>  还有一个与局部施用关系密切的概念——柯里化（Currying，这个名字大概来自于数理逻辑学家 *Haskell Brooks Curry*）。柯里化的函数每次只接受一个参数，把这个参数局部施用，然后返回接受“余下参数”的函数，返回的函数也是柯里化的；直到最后返回一个值。
>
>  一个例子就是下面的 `onCallPartialApplyReadFile` 函数，它其实就是柯里化之后的 `fs.readFile`。

我们这样改写 `fs.readFile` ：

```javascript
const fs = require('fs');
// 接受 file 参数，然后返回接受 callback 的函数
const onCallPartialApplyReadFile = file => callback => fs.readFile(file, callback);
function concatFile3(file1, file2, file3) {
  const dataCPS1 = onCallPartialApplyReadFile(file1);
  const dataCPS2 = onCallPartialApplyReadFile(file2);
  const dataCPS3 = onCallPartialApplyReadFile(file3);
  return callback => dataCPS1((err1, data1) => {
   	dataCPS2((err2, data2) => {
      dataCPS3((err3, data3) => {
        let e;
        if (e = err1 || err2 || err3) {
          callback(e);
          return;
        }
        callback(null, `${data1}${data2}${data3}`);
      })
    })
  })
}
```

在这里，`dataCPSx` 是一个仅仅接受一个回调函数的函数。在获得回调函数之后，他会将蕴藏在其中的值（也可能是错误）无私地交给回调函数。

`dataCPSx` 完全不接受多余的参数——它的参数仅仅只有一个回调函数而已。他就像是一个盒子，封印着本该属于我们的文件。而获得那东西的方式呢？就是传递进去一个回调函数。虽然在我们和文件之间隔了一层隔阂，但是说到底，认为 `dataCPSx` 是值、是变量、是我们要打开的文件本身是完全没问题的吧——毕竟，我们只要传递一个回调函数，就可以立即获得我们的文件。

现在我们可以这样用 `concatFile3`：

```javascript
let withConcatedFile = concatFile3(\"foo.txt\", \"bar.txt\", \"baz.txt\")
withConcatedFile(data => console.log(data));
//               ^^^^ 这就是我们的文件！
```

读到这里，你可能感觉被骗了，毕竟我们的代码比以前更加冗长了，而且 > 形状的代码和冗余的错误处理丝毫没有改观。

但是应该注意到好的一面：现在，比起最初完全依赖于副作用来进行的函数，我们的函数拥有了返回值。这意味它有了更加接近传统函数的可能：接受输入，给出输出，如此而已。接下来，通过对我们返回的这个函数（就是那个接受回调函数的函数。读起来很绕口，思考起来也有点绕！）进行抽象，我们将会目见许多新的奇妙事物。

# 封装返回值

直接操作函数可能让一些精于面向对象的程序员们有些不安。另一方面，也不太利于我们对他的拓展。（虽然我们大可像 lisp 程序员那样写直接操纵函数的辅助函数……究竟怎样做，大概是个人选择……）

我们将那个接受回调函数，然后施用值于它的函数，或者说，那个“表现得有点奇怪的值”——`dataCPSx`，封装进一个类中：

```javascript
class Async {
  /* 这里 innerCPSValue 的类型是 callback => void */
  /* 而 callback 的类型则是 (err, data) => void */
  constructor(innerCPSValue) {
    this.innerCPSValue = innerCPSValue;
  }
  /* callWithIt 会调用内部的函数；即将内部封存的值传递给回调函数。 */
  callWithIt(callback) {
    this.innerCPSValue(callback);
  }
}

const fs = require('fs');
readFileAsync = file => new Async(callback => fs.readFile(file, callback))
//                                ^^^^^^^^^^^^^^原本的返回值^^^^^^^^^^^^^^^ 
//                      -----------------------如今的返回值-----------------
//                      原本的返回值如今被封装到了 Async 对象中。
```

这个类和原先的函数是等同的，因此不会有太多改观。

不过，我们可以以之为营，作出一些改变。

首先，原先的所有回调函数接受两个值：一个错误时的异常，还有一个是成功时的数据。不过事实上，他们很少会有真正同时返回的时候。大多数时候，其中有一个会是 `null` ；换句话说，我们处理成功和处理失败的逻辑，几乎不会有一起被启动的场景（回忆一下，以前的 try-catch 结构是不是也是这样？）。

于是可以这样修改 `Async` 类：

```javascript
class Async {
  // constructors...
  callWithIt(success, failed) {
    this.innerCPSValue((err, data) => {
      if (err) {
     		if (typeof failed === 'function') failed(err);
        else throw err;
      } else {
      	success(data);
      }
    });
  }
}
```

`callWithIt` 在回调函数外裹上了一层包装，现在，`callWithIt` 接受两个回调函数。一个是成功时的回调，另一个是失败时的回调。同时我们保证，在逻辑上，只会有一个回调函数被调用。

> 在代数数据类型的观念下，这种作为是将原本是**积类型**的错误 `(Error, Data)` 二元组变成了**和类型**的错误 `Either[Error, Data]`。后者类似于联合体类型，它保证同时只会出现一个类型的值。于是便不会出现“错误正确叠加态”，因此我们能够分离处理正确和错误的逻辑——将它们放到两个不同的函数中去。

现在，我们的风格成了这样：

```javascript
const fs = require('fs');
readFileAsync = file => new Async(callback => fs.readFile(file, callback))

readFileAsync(__filename).callWithIt(
    data => console.log(`readed: ${data.toString()}`),
		err => console.error(`err: ${err.message}`) 
)
```

看起来简洁了一些，因为我们将那串 `if (err) {...}` 的模式化代码交给了 `Async` 类本身。

# 重用模式化的代码

再请出我们的老朋友，`peaceAndLove` 来看看：

```javascript
function peaceAndLove(file) {
  const asyncData = readFailAsync(file);
  return new Async(callback => asyncData.callWithIt( // <- 创建新的一个 Async 对象
  	data => callback(null,  // 这个新的 Async 在将值传递给回调函数之前会先做一些处理。
 		  data.toString().replace(/fuck/i, \"love\") // <- 只有这句话里面有 peaceAndLove 的逻辑。
    ),
    err => callback(err)
  ));
}
```

错误仍旧没有默认行为，而且手动调用 `new`、生成新对象、注入处理之后的值的操作过度模式化了。

于是，我们可以将一部分逻辑抽离到单独的方法中去：

```javascript
class Async {
  //... old functions
  /* map 在成功的值传递给回调函数之前附加上一个运算。 */
  map(f) {
    return new Async(callback => this.callWithIt( // <- 创建新的 Async
      data => callback(null, f(data)), // <- 如果自身成功了，就用 f 做处理，然后再给回调函数。
      err => callback(err) // <- 否则，什么都不做，直接将失败交给回调函数。
    ));
  }
  
  /* mapErr 在失败的值传递给回调函数之前加上一个处理，和 map 十分类似。 */
  mapErr(h) {
    return new Async(callback => this.callWithIt(
    	data => callback(null, data),
      err => callback(h(err))
    ))
  }
}
```

>  `map` 这个函数对于 `Async` 类来说有着特殊的意义——我们提到过，`Async` 对象表示一个特殊的值。更加具体地说，它是装在某个由上下文（成功还是失败，以及对应的回调）组成的盒子里的值。如果把 `Async` 比作盒子，`callWithIt` 比作用锤子将盒子砸碎，然后取出里面的值来的话；`map` 则给予了我们“隔山打牛”的力量。我们可以通过传递函数来操纵其中的值，这意味着我们能够对它做一切函数能做的事情——`Async` 内封印的值已经与外边的世界完全同态了！完全可以在 `map` 中调用 `console.log` 一类的函数，甚至可以借助闭包的力量将值直接传递到外部去（虽然不建议这样做）！
>
>  当然，从 `map` 的实现中可以看出来，这一切只会在我们调用 `callWithIt` 之后发生。

回到眼下，我们可以这样写 `peaceAndLove` 了……

```javascript
const fs = require('fs');
readFileAsync = file => new Async(callback => fs.readFile(file, callback))
function peaceAndLove(file) {
  const asyncData = readFileAsync(file);
  return asyncData.map(stream => stream.toString().replace(/fuck/i, \"love\"));
}
```

已经几乎没有冗余代码了。

再来看看 `concatFile3` ……的弟弟 `concatFile2`，我们故技重施：

```javascript
function concatFile2(file1, file2) {
  const asyncData1 = readFileAsync(file1);
  const asyncData2 = readFileAsync(file2);
  return asyncData1.map(data1 => 
    asyncData2.map(data2 => 
      `${data1}${data2}`
  ))
}
```

来试试看行不行：

```javascript
concatFile2(__filename, __filename).callWithIt(data => console.log(data));
```

输出了什么？

```
Async { innerCPSValue: [Function] }
```

……通过不懈的努力，我们获得了双倍的 `Async`！

就像俄罗斯套娃一样，这个 `Async` 的 `callWithIt` 会将另一个 `Async` 类型的家伙传递给成功回调！

聪明的我们马上想到这样写：

```javascript
concatFile2(__filename, __filename)
  .callWithIt(data => 
              data.callWithIt(readData => console.log(readData));
```

这样的代码也有点模式化了，因此我们可以也将其作为 `Async` 类的一个方法：

```javascript
class Async {
  // ... old codes
  /* flatten 压平上文提到的“俄罗斯套娃”结构。 */
  flatten() {
    return new Async(callback => this.callWithIt( // <- 仍旧是创建新的 Async
      asyncData => asyncData.callWithIt( // <- 拆开 Async 中的 Async
        data => callback(null, data), 
        err => callback(err)), 
      err => callback(err))) // <- 只要二者（自身内部，自身）有一个出现错误，就会直接触发错误回调。
  }
}
```

> `flatten`（或者 `flatMap`，二者可以相互实现。）对于 `Async` 类而言也有着特别的意义——它允许我们组合任意个返回 `Async` 对象的计算（也就是异步计算）。如果说 `map` 允许我们任意操纵同一个“盒子”包裹着的值的话，`flatten` 则赋予了我们将两个不同“盒子”合二为一的魔法。
>
> 还请注意，这些魔法都必须经由 `Async` 类本身实现。也就是说，并不是所有的“盒子”都能提供这样的魔力。

我们还可以顺手组合一下 `map` 和 `flatten` ：

```javascript
class Async {
  // ... old codes
  flatMap(f) {
    return this.map(f).flatten();
  }
  
  flatMapErr(h) {
    return this.map(h).flatten();
  }
}
```

# 构造新的语法

再一次，请老大哥 `concatFile3` 出场：

```javascript
const fs = require('fs');
readFileAsync = file => new Async(callback => fs.readFile(file, callback))
function concatFile3(file1, file2, file3) {
	return readFileAsync(file1).flatMap( data1 => 
           readFileAsync(file2).flatMap( data2 => 
             readFileAsync(file3).map( data3 => 
               `${data1}${data2}${data3}`)))
}
```

全新的 `concatFile3` 有了两处改观：其一是错误有了默认的行为——借助 `map` 和 `flatMap` 的帮助，在 `map` 一个失败的 `Async` 的时候，什么都不会发生，而当我们想要“转换”或者“预处理”错误的时候，我们可以用 `mapErr` 和 `flatMapErr`。其二是我们的代码中“逻辑”的密度上升了不少——因为那些样板代码都在 `map` 和 `flatmap` 中了。

另一方面，我们的代码还有了一丝令人怀念的气息：每一处 `flatMap` 就像是一次赋值一样，假如我们对这个函数做一下变形……

先增加一些方法：

```javascript
class Async{
  // ... old codes
  /* unit 将一个普通的值包装成 Async 类的值，创造一个马上成功的 Async。*/
  static unit(item) {
  	return new Async(callback => callback(null, item));
  }

  /* 创造一个立即失败的 Async。 */
  static fail(err) {
  	return new Async(callback => callback(err));
  }
}
```

> `unit` 也是有着特殊意义的函数， 它召来了“空上下文”。我们可以将任意一个值安装到由“空上下文”构成的盒子中去。

接下来，把最后一个 `map` 换成 `flatMap`，再来看看我们的 `concatFile3` 老大哥。

```javascript
const fs = require('fs');
readFileAsync = file => new Async(callback => fs.readFile(file, callback))
function concatFile3(file1, file2, file3) {
	return readFileAsync(file1).flatMap( data1 => // data1 <- readFileAsync(file1)
         readFileAsync(file2).flatMap( data2 => // data2 <- readFileAsync(file2)
         readFileAsync(file3).flatMap( data3 => // data3 <- readFileAsync(file3)
         Async.unit(`${data1}${data2}${data3}`)))) // return `${data1}${data2}${data3}`
}
```

现在，每一行都有了全新的意义：每一处 `flatMap` 就像是把藏在 `Async` 中的值抽取出来了一般；而这一切操作的结果必须也是一个 `Async`。因此对于一个普通的值来说，`unit` 就像是 `return` 一般。

所以，试着来增加一些语法规则将其变成我们真正熟悉的那样吧。

**第一个规则是 `await`**。

每一行 `await someAsyncValue` 都可以将其翻译为 `someAsyncValue.flatMap( __var1 => {...} )`。

其中，`...` 中承载着的就是之后的代码，同时将其中每一个用到 `await someAsyncValue` 的地方换成 `__var1` ，例如：

```javascript
function readData(file1) { 
	const data = await readFileAsync(file1);
	// 剩余部分的代码……
}
```

可以被翻译为：

```javascript
function readData(file1) {
  return readFileAsync(file1).flatMap(__var1 => {
    const data = __var1;
    // 剩余部分的代码……
  })
}
```

在我们的使用者看来，`await someAsyncValue` 就好像是会直接返回包裹在 `Async` 内部的值一般。另外，我们必须把 `return` 提前到第一个 `await` 之前，不过这反倒是细枝末节的事情了。

但是，还有一个问题：传入 `flatMap` 的函数的返回类型必须是 `Async`。

因此，**我们在函数声明前面加上 `async` 以区分；这就是第二个语法规则**。我们保证，具有这个标志的函数必须返回 `Async` 值，若不然，我们会在 `return` 前面加上 `unit`：

```javascript
async function theUniverse() {
	return 42;
}
```

会被视作：

```javascript
function theUniverse() {
  return Async.unit(42);
}
```

同时，为了阻止返回未经包装的值（事实上，我们根本做不到返回未经包装的值！），**我们仅仅允许在 `async` 函数内部使用 `await`**。

这样一来，`concatFile3` 可以这样写：

```javascript
const fs = require('fs');
readFileAsync = file => new Async(callback => fs.readFile(file, callback))

async function concatFile3(file1, file2, file3) {
  const data1 = await readFileAsync(file1);
  const data2 = await readFileAsync(file2);
  const data3 = await readFileAsync(file3);
  return `${data1}${data2}${data3}`;
}
```

几乎已经和同步时一样了。

# 中途站

看起来，我们的伙伴 `Async` 已经达到了我们的目标了。它挪走了三座大山：冗余的异常处理、诡异的返回方式和 > 形状的代码。最终，`concatFile3` 已经和同步时相当地相似了。我们似乎已经战胜了回调地狱，夺回了符合直觉的命令式编程习惯。

但事实上，如果你把最终版本的代码粘贴到 `node` 中去，几乎肯定是无法运行的。因为我们没有修改 Javascript 语法的力量。虽然 `Async` 类的之前的一切都可以做到，但是最后我们会止步于 `map/flatMap` 的世界中。最后的 `async/await` 不过是幻梦罢了。

……

不过你也可能注意到了：上面的代码中，`async` 和 `await` 被高亮了——倒也不用卖关子了（你多半也早就知道了），ES6 的标准中，增加了对 `async/await` 的支持；ES6 中用来替代 `Async` 类的东西有着非常美的名字：`Promise`。我自己的观念中，这个名字暗示了它是尚未完成，但是却**保证**会在将来有结果的计算。

实现 `Promise` 的人们借助操纵语言本身的力量还有他们的深思熟虑，让 `Promise` 比我们的 `Async` 要成熟不少。（还请注意，`Promise` 的实现应该和我们的 `Async` 有不少不同，即便他们用起来看上去有点像）事实上，上面提到的所有 `Async` 能做到的东西，我们都可以用 `Promise` 做到（而且多半能做得更好）。

但是我们先休息一会儿吧。在再度起航之后，我们会遇见 `Promise` —— Javascript 中真正的 `Async`。还有两个在函数式语言中极其重要的抽象：`Functor` 和 `Monad`；它们可以被理解成所有“被上下文包裹的值”的类型的抽象（在范畴论中则又有一些不尽然相同的解释），有了它们的帮助，我们会发现 `async/await` 模式可以应用到更多地方去：列表计算、函数计算、不使用 try-catch 的异常处理、甚至是语法解析器……

不过那些都是未知的未来的事情了。如今，好好歇会儿吧。

> 最后的一些话：
>
> - 我们没有实现 `Async` 类（或许，现在可以说它另一个常用的名字—— `Cont` 了）十分重要的一个方法—— `callWithCurrentContinuation` ，在 `scheme` 中，它也被叫做 `call/cc`。这个方法将它被调用的时候的 continuation 注入给传入它的函数，这个函数可以成为实现属于我们的协程（coroutine）的关键。详细的状况可以参考维基百科（如果你懂 lisp 的话）。
> - 如果你对 `Functor` 和 `Monad` 抽象感兴趣的话，可以直接阅读 [functors, applicatives, and monads in pictures.](http://adit.io/posts/2013-04-17-functors,_applicatives,_and_monads_in_pictures.html#translations) 这篇文章有多个编程语言版本的翻译。
> - 关于 `Promise` 的使用的文章网上有相当多。你可以阅读[MDN 的文档](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/promise) ，也可以参考其他博文。
> - 事实上，我也不知道我们的旅途何时会再度开始。